const grid=document.getElementById('grid'),empty=document.getElementById('empty'),viewer=document.getElementById('viewer'),viewerImg=document.getElementById('viewerImg'),closeViewer=document.getElementById('closeViewer'),photoInput=document.getElementById('photoInput'),uploadButton=document.getElementById('uploadButton'),uploadStatus=document.getElementById('uploadStatus'),modes=document.querySelectorAll('#modes button');
const REPO='mrkritor-ui/IPHONE5C',BRANCH='main',API='https://api.github.com',TOKEN_KEY='iphone5c_github_token';
let photos=[],current=0;
const photoUrl=n=>`photos/${encodeURIComponent(n).replace(/%2F/g,'/')}`;
const formatBytes=b=>b<1048576?`${Math.round(b/1024)} KB`:`${(b/1048576).toFixed(1)} MB`;
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
function render(){grid.innerHTML='';empty.classList.toggle('hidden',photos.length!==0);photos.forEach((n,i)=>{const img=document.createElement('img');img.loading=i<12?'eager':'lazy';img.decoding='async';img.src=photoUrl(n);img.alt=n;img.onclick=()=>openViewer(i);grid.appendChild(img)})}
function openViewer(i){current=i;viewerImg.src=photoUrl(photos[i]);viewerImg.alt=photos[i];viewer.classList.remove('hidden')}
function close(){viewer.classList.add('hidden');viewerImg.src=''}
function move(d){if(!photos.length)return;current=(current+d+photos.length)%photos.length;viewerImg.src=photoUrl(photos[current]);viewerImg.alt=photos[current]}
closeViewer.onclick=close;viewer.onclick=e=>{if(e.target===viewer)close()};
document.addEventListener('keydown',e=>{if(viewer.classList.contains('hidden'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
let sx=0;viewer.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});viewer.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)move(dx<0?1:-1)},{passive:true});
modes.forEach(b=>b.onclick=()=>{modes.forEach(x=>x.classList.remove('active'));b.classList.add('active');grid.style.setProperty('--cols',b.dataset.cols)});grid.style.setProperty('--cols','4');

const modal=document.getElementById('uploaderModal'),setup=document.getElementById('setupUploader'),tokenInput=document.getElementById('tokenInput'),saveToken=document.getElementById('saveToken'),cancel=document.getElementById('cancelUploader'),clearToken=document.getElementById('clearToken'),tokenStatus=document.getElementById('tokenStatus');
function showSetup(){modal.classList.remove('hidden');tokenInput.value='';tokenStatus.textContent='';setTimeout(()=>tokenInput.focus(),100)}
function hideSetup(){modal.classList.add('hidden')}
setup.onclick=showSetup;cancel.onclick=hideSetup;clearToken.onclick=()=>{localStorage.removeItem(TOKEN_KEY);tokenStatus.textContent='Token forgotten.'};
async function testToken(t){const r=await fetch(`${API}/repos/${REPO}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`}});if(!r.ok){let j={};try{j=await r.json()}catch{}throw new Error(j.message||`GitHub returned ${r.status}`)}return true}
saveToken.onclick=async()=>{const t=tokenInput.value.trim();if(!t)return;saveToken.disabled=true;tokenStatus.textContent='Testing…';try{await testToken(t);localStorage.setItem(TOKEN_KEY,t);tokenStatus.textContent='Ready.';setTimeout(hideSetup,400)}catch(e){tokenStatus.textContent=`Not working: ${e.message}`}finally{saveToken.disabled=false}};

uploadButton.onclick=()=>{if(!token()){showSetup();return}photoInput.click()};
async function optimise(file){const bm=await createImageBitmap(file,{imageOrientation:'from-image'}).catch(()=>null);if(!bm)return file;const max=1800,s=Math.min(1,max/Math.max(bm.width,bm.height)),c=document.createElement('canvas');c.width=Math.round(bm.width*s);c.height=Math.round(bm.height*s);c.getContext('2d',{alpha:false}).drawImage(bm,0,0,c.width,c.height);bm.close();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.78));if(!blob)return file;const base=(file.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'_')||'photo');return new File([blob],`${base}.jpg`,{type:'image/jpeg'})}
function b64(bytes){let s='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(s)}
async function uploadFile(file,i,total){const content=b64(new Uint8Array(await file.arrayBuffer()));const path=`photos/${file.name}`;const r=await fetch(`${API}/repos/${REPO}/contents/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token()}`,'Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:JSON.stringify({message:`Add ${file.name}`,content,branch:BRANCH})});if(!r.ok){let j={};try{j=await r.json()}catch{}throw new Error(j.message||`GitHub upload failed (${r.status})`)}uploadStatus.textContent=`Uploaded ${i}/${total}`}
photoInput.onchange=async()=>{const files=[...photoInput.files].filter(f=>f.type.startsWith('image/'));if(!files.length)return;if(!token()){showSetup();photoInput.value='';return}try{let before=0,after=0,out=[];for(let i=0;i<files.length;i++){before+=files[i].size;uploadStatus.textContent=`Compressing ${i+1}/${files.length}…`;const f=await optimise(files[i]);after+=f.size;out.push(f)}uploadStatus.textContent=`Compressed ${formatBytes(before)} → ${formatBytes(after)}`;for(let i=0;i<out.length;i++)await uploadFile(out[i],i+1,out.length);uploadStatus.textContent=`Done — ${out.length} photo${out.length===1?'':'s'} uploaded`;setTimeout(loadPhotos,1500)}catch(e){console.error(e);uploadStatus.textContent=`Upload failed: ${e.message}`}photoInput.value=''};
async function loadPhotos(){try{const r=await fetch(`photos/photos.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`manifest ${r.status}`);photos=await r.json();if(!Array.isArray(photos))throw Error('invalid manifest');render()}catch(e){console.error(e);photos=[];render()}}loadPhotos();
