const grid=document.getElementById('grid'),empty=document.getElementById('empty'),viewer=document.getElementById('viewer'),viewerImg=document.getElementById('viewerImg'),closeViewer=document.getElementById('closeViewer'),photoInput=document.getElementById('photoInput'),uploadButton=document.getElementById('uploadButton'),uploadStatus=document.getElementById('uploadStatus'),modes=document.querySelectorAll('#modes button');
const REPO='mrkritor-ui/IPHONE5C',BRANCH='main',API='https://api.github.com',TOKEN_KEY='iphone5c_github_token';let photos=[],current=0;
const photoUrl=n=>`photos/${encodeURIComponent(n).replace(/%2F/g,'/')}`,formatBytes=b=>b<1048576?`${Math.round(b/1024)} KB`:`${(b/1048576).toFixed(1)} MB`,token=()=>localStorage.getItem(TOKEN_KEY)||'';
function render(){grid.innerHTML='';empty.classList.toggle('hidden',photos.length!==0);photos.forEach((n,i)=>{const img=document.createElement('img');img.loading=i<12?'eager':'lazy';img.decoding='async';img.src=photoUrl(n);img.alt=n;img.onclick=()=>openViewer(i);grid.appendChild(img)})}function openViewer(i){current=i;viewerImg.src=photoUrl(photos[i]);viewerImg.alt=photos[i];viewer.classList.remove('hidden')}function close(){viewer.classList.add('hidden');viewerImg.src=''}function move(d){if(!photos.length)return;current=(current+d+photos.length)%photos.length;viewerImg.src=photoUrl(photos[current]);viewerImg.alt=photos[current]}
closeViewer.onclick=close;viewer.onclick=e=>{if(e.target===viewer)close()};document.addEventListener('keydown',e=>{if(viewer.classList.contains('hidden'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});let sx=0;viewer.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});viewer.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)move(dx<0?1:-1)},{passive:true});modes.forEach(b=>b.onclick=()=>{modes.forEach(x=>x.classList.remove('active'));b.classList.add('active');grid.style.setProperty('--cols',b.dataset.cols)});grid.style.setProperty('--cols','4');
const pinModal=document.getElementById('pinModal'),pinInput=document.getElementById('pinInput'),pinButton=document.getElementById('pinButton'),pinStatus=document.getElementById('pinStatus'),tokenModal=document.getElementById('tokenModal'),tokenInput=document.getElementById('tokenInput'),saveToken=document.getElementById('saveToken'),cancelToken=document.getElementById('cancelToken'),tokenStatus=document.getElementById('tokenStatus'),setup=document.getElementById('setupUploader');
function showPin(){pinInput.value='';pinStatus.textContent='';pinModal.classList.remove('hidden');setTimeout(()=>pinInput.focus(),100)}function hidePin(){pinModal.classList.add('hidden')}function showToken(){tokenInput.value='';tokenStatus.textContent='';tokenModal.classList.remove('hidden');setTimeout(()=>tokenInput.focus(),100)}
setup.onclick=showToken;cancelToken.onclick=()=>tokenModal.classList.add('hidden');
async function testToken(t){const r=await fetch(`${API}/repos/${REPO}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`}});if(!r.ok){let j={};try{j=await r.json()}catch{}throw Error(j.message||`GitHub returned ${r.status}`)}return true}
saveToken.onclick=async()=>{const t=tokenInput.value.trim();if(!t){tokenStatus.textContent='Enter a token.';return}saveToken.disabled=true;tokenStatus.textContent='Testing…';try{await testToken(t);localStorage.setItem(TOKEN_KEY,t);tokenStatus.textContent='Saved.';setTimeout(()=>tokenModal.classList.add('hidden'),500)}catch(e){tokenStatus.textContent=`Not working: ${e.message}`}finally{saveToken.disabled=false}};
function startUpload(){if(!token()){showToken();return}photoInput.click()}uploadButton.onclick=showPin;pinButton.onclick=()=>{if(pinInput.value==='1234'){hidePin();startUpload()}else{pinStatus.textContent='Wrong PIN.';pinInput.select()}};pinInput.onkeydown=e=>{if(e.key==='Enter')pinButton.click()};
async function optimise(file){const bm=await createImageBitmap(file,{imageOrientation:'from-image'}).catch(()=>null);if(!bm)return file;const max=1800,s=Math.min(1,max/Math.max(bm.width,bm.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bm.width*s));c.height=Math.max(1,Math.round(bm.height*s));c.getContext('2d',{alpha:false}).drawImage(bm,0,0,c.width,c.height);bm.close();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.78));if(!blob)return file;const base=(file.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'_')||'photo');return new File([blob],`${base}.jpg`,{type:'image/jpeg'})}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+32768,bytes.length)));return btoa(s)}
async function uploadFile(file,i,total){const content=b64(new Uint8Array(await file.arrayBuffer())),path=`photos/${file.name}`,encoded=path.split('/').map(encodeURIComponent).join('/');let sha;const ex=await fetch(`${API}/repos/${REPO}/contents/${encoded}?ref=${BRANCH}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token()}`}});if(ex.ok)sha=(await ex.json()).sha;const body={message:`Add ${file.name}`,content,branch:BRANCH};if(sha)body.sha=sha;const r=await fetch(`${API}/repos/${REPO}/contents/${encoded}`,{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token()}`,'Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:JSON.stringify(body)});if(!r.ok){let j={};try{j=await r.json()}catch{}throw Error(j.message||`GitHub upload failed (${r.status})`)}uploadStatus.textContent=`Uploaded ${i}/${total}`}
photoInput.onchange=async()=>{const files=[...photoInput.files].filter(f=>f.type.startsWith('image/'));if(!files.length)return;try{let before=0,after=0,out=[];for(let i=0;i<files.length;i++){before+=files[i].size;uploadStatus.textContent=`Compressing ${i+1}/${files.length}…`;const f=await optimise(files[i]);after+=f.size;out.push(f)}uploadStatus.textContent=`Compressed ${formatBytes(before)} → ${formatBytes(after)}`;for(let i=0;i<out.length;i++)await uploadFile(out[i],i+1,out.length);uploadStatus.textContent=`Done — ${out.length} uploaded`;setTimeout(loadPhotos,2500)}catch(e){console.error(e);uploadStatus.textContent=`Upload failed: ${e.message}`}photoInput.value=''};
async function loadPhotos(){try{const r=await fetch(`photos/photos.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`manifest ${r.status}`);photos=await r.json();if(!Array.isArray(photos))throw Error('invalid manifest');render()}catch(e){console.error(e);photos=[];render()}}loadPhotos();
